# Generated by Django 3.2.14 on 2022-07-24 20:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0009_auto_20220723_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock()), ('specifications', wagtail.blocks.RichTextBlock())], use_json_field=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность товара')),
                ('article', models.CharField(max_length=256, verbose_name='Артикул')),
                ('image', wagtail.fields.StreamField([('images', wagtail.images.blocks.ImageChooserBlock(help_text='Изображения товара'))], use_json_field=None)),
                ('price_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара со скидкой')),
                ('sale', models.BooleanField(default=False, verbose_name='Индикатор активности скидки')),
                ('brand_fk', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='brand.brand', verbose_name='Бренд')),
                ('category_fk', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='home.category', verbose_name='Категория')),
                ('rubric_fk', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_products', to='home.rubric', verbose_name='Рубрика')),
                ('sizes_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Размерная сетка')),
                ('subcategory_fk', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_products', to='home.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            bases=('wagtailcore.page',),
        ),
    ]
