# Generated by Django 4.0.6 on 2022-07-23 13:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_rubric_subcategory_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_fk',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='home.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название подкатегории'),
        ),
    ]
