# Generated by Django 4.0.6 on 2022-07-23 13:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subcategory_category_fk_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='subcategory_fk',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics', to='home.subcategory', verbose_name='Рубрика'),
        ),
    ]
