# Generated by Django 3.2.14 on 2022-07-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_rubric_subcategory_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='subcategory_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics', to='home.subcategory', verbose_name='Рубрика'),
        ),
    ]
