# Generated by Django 3.2.14 on 2022-07-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_rubric_subcategory_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='home.category', verbose_name='Категория'),
        ),
    ]
