# Generated by Django 3.2.14 on 2022-07-23 15:24

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_subcategory_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='subcategory_fk',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics', to='home.subcategory', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_fk',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='home.category', verbose_name='Категория'),
        ),
    ]
