# Generated by Django 3.2.14 on 2022-07-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('home', '0010_categoriesindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriesIndex',
        ),
    ]
